extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  comments:
    min-spaces-from-content: 1
  
  comments-indentation: disable
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false
  
  key-duplicates: enable
  
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  new-line-at-end-of-file: enable
  
  trailing-spaces: enable

ignore: |
  .github/
  node_modules/
  .git/
  .venv/
  __pycache__/
  *.pyc 