# Default values for rag-system
# This is a YAML-formatted file.

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []

# Frontend configuration
frontend:
  enabled: true
  image:
    repository: rag-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: rag-system.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: rag-system-tls
        hosts:
          - rag-system.example.com
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Backend configuration
backend:
  enabled: true
  image:
    repository: rag-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  
  env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: rag-secrets
          key: database-url
    - name: REDIS_URL
      value: "redis://redis:6379"
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: rag-secrets
          key: openai-api-key
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "password"
    database: "rag_db"
  primary:
    persistence:
      enabled: true
      size: 10Gi

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi

# Milvus configuration (external)
milvus:
  enabled: false
  host: "milvus"
  port: 19530

# Monitoring
monitoring:
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80 