apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag-system.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-system.labels" . | nindent 4 }}
data:
  # Database configuration
  DB_HOST: {{ .Values.config.database.host | quote }}
  DB_PORT: {{ .Values.config.database.port | quote }}
  DB_NAME: {{ .Values.config.database.name | quote }}
  DB_USERNAME: {{ .Values.config.database.username | quote }}
  
  # Redis configuration
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
  
  # S3 configuration
  AWS_REGION: {{ .Values.config.aws.region | quote }}
  S3_BUCKET_NAME: {{ .Values.config.s3.bucketName | quote }}
  
  # Application configuration
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  
  # Vector database configuration
  {{- if .Values.config.vectorDB }}
  VECTOR_DB_TYPE: {{ .Values.config.vectorDB.type | quote }}
  VECTOR_DB_HOST: {{ .Values.config.vectorDB.host | quote }}
  VECTOR_DB_PORT: {{ .Values.config.vectorDB.port | quote }}
  {{- end }}
  
  # AI model configuration
  {{- if .Values.config.aiModel }}
  AI_MODEL_PROVIDER: {{ .Values.config.aiModel.provider | quote }}
  AI_MODEL_NAME: {{ .Values.config.aiModel.name | quote }}
  EMBEDDING_MODEL: {{ .Values.config.aiModel.embeddingModel | quote }}
  {{- end }} 