apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-system.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rag-system.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.databasePassword }}
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisAuthToken }}
  redis-auth-token: {{ .Values.secrets.redisAuthToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- end }} 